name: Publish Docker image
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build
        run: |
          docker run --rm --privileged tonistiigi/binfmt:latest --install all
          docker buildx create --use --name=multibulider --driver docker-container --driver-opt image=moby/buildkit:master
          docker buildx use multibulider
          docker buildx build --platform linux/arm,linux/arm64,linux/amd64 -t tofuliang/smartdns:latest . --push
